channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=23.2
- pip:
  - mlflow<3,>=2.9.2
  - cffi==1.15.1
  - click==8.1.3
  - cloudpickle==3.0.0
  - colorama==0.4.6
  - dataclasses==0.6
  - dash==2.9.3
  - dash-bootstrap-components==1.4.1
  - defusedxml==0.7.1
  - distributed==2023.2.0
  - gunicorn==20.1.0
  - jinja2==3.1.2
  - lightgbm==3.3.5
  - matplotlib==3.7.1
  - numpy==1.20.0
  - packaging==23.2
  - pandas==1.4.4
  - pyarrow==6.0.1
  - pyyaml==6.0
  - scikit-learn==1.4.0
  - scipy==1.10.1
  - typing-extensions==4.5.0
  - xgboost==1.7.6
name: mlflow-env
